### PR TITLE
[release-4.7] Bug 2046237: update go.mod for go1.15

### PR DESCRIPTION
**Pull request by joelddiaz**
This is what ART is building with for release-4.7, so make local builds
match what ART is doing.

Use go 1.15; go mod vendor ; go mod tidy ; go list -find ./... ; and commit the changes.

### CODE REVIEW

**Review by akhil-rane — COMMENTED** [review]
Do we want to set the minimum version in go.mod to 1.15?

**Comment by joelddiaz** [comment]
> Do we want to set the minimum version in go.mod to 1.15?

I was told that ART build with go 1.15 for release-4.7 (and release-4.6).

**Review by akhil-rane — COMMENTED** [review]
/lgtm

**Comment by lwan-wanglin** [comment]
verified with cluster-bot image(4.7.0-0.ci.test-2022-01-29-014157-ci-ln-5npw5tt-latest) with the PR merged, no regression found.
no pending CSR created by pod-identity-webhook
$ oc get csr
No resources found
test run:
OS-20220129-1128
logs:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/293755/consoleFull

/label qe-approved
/label cherry-pick-approved

**Pull request merged**
