### PR TITLE
Bug 1875353: UPSTREAM: 70: Fix panic in cache informer

### PR DESCRIPTION
**Pull request by sjenning**
@mfojtik @derekwaynecarr 

xref https://bugzilla.redhat.com/show_bug.cgi?id=1875353
xref https://github.com/aws/amazon-eks-pod-identity-webhook/pull/70

### CODE REVIEW

**Comment by mfojtik** [comment]
@sjenning please repick :-) goimports failed me.

**Comment by sjenning** [comment]
@mfojtik resynced

**Pull request merged**
