### PR TITLE
OCPBUGS-21761: Backport the recent rebase to 4.14

### PR DESCRIPTION
**Pull request by dlom**
/assign @jstuever 
/cc @abutcher 

xref: [OCPBUGS-21761](https://issues.redhat.com/browse/OCPBUGS-21761)

### CODE REVIEW

**Comment by 2uasimojo** [comment]
@dlom I don't think I'm qualified to review the backport part of this. If you want to pull out the vuln dep bumps I'm happy to hit that one, but I think the rest should be the province of...

/assign @jstuever

**Comment by jstuever** [comment]
Added oidc jobs so we can test here.
https://github.com/openshift/release/pull/45184

**Comment by dlom** [comment]
@sdodson is there anything we can do to get the `cherry-pick-approved` labeling privileges?

**Comment by sdodson** [comment]
@dlom that label should come from your QE team, do you have a contact that you normally work with to QE this component?

Sorry if I missed that above, having trouble loading all comments on my phone right now.

**Comment by dlom** [comment]
> do you have a contact that you normally work with to QE this component?

I think so, I'll try to track them down

**Comment by dlom** [comment]
/assign @jianping-shu 

Can we please get a `cherry-pick-approved` label from QE?

**Comment by jianping-shu** [comment]
verified with cluster-bot, aws cluster installed successfully. Regression tested with OCP-57437/36498/50869/48360/45975/34470.

**Comment by YuLi517** [comment]
Based on the request in comment of [OCPBUGS-3376](https://issues.redhat.com/browse/OCPBUGS-3376), could we cherry-pick to 4.12.z?

**Pull request merged**
