### PR TITLE
[release-4.9] Bug 2026379: update go.mod for go1.16

### PR DESCRIPTION
**Pull request by joelddiaz**

### CODE REVIEW

**Comment by joelddiaz** [comment]
/assign @akhil-rane 
these will be all manual backports ¯\_(ツ)_/¯

**Review by akhil-rane — COMMENTED** [review]
/lgtm

**Comment by joelddiaz** [comment]
@lwan-wanglin is this backport on your BZs-to-verify list?

**Comment by lwan-wanglin** [comment]
Tested today, sorry for missing this one.
Verified steps are in [Bug 2026379#c1](https://bugzilla.redhat.com/show_bug.cgi?id=2026379#c1)

/label qe-approved
/label backport-risk-assessed
/approve

**Comment by lwan-wanglin** [comment]
@joelddiaz need label backport-risk-assessed

**Comment by joelddiaz** [comment]
@lwan-wanglin with https://github.com/openshift/release/pull/24245 merged, you should be able to do the ckerry-pick-approved now (and I should be able to backport-risk-assessed)

**Comment by lwan-wanglin** [comment]
Thanks joel.
/label cherry-pick-approved

**Pull request merged**
