### PR TITLE
update go.mod for go 1.16

### PR DESCRIPTION
**Pull request by joelddiaz**
update go.mod for 1.16 and run 'go mod vendor ; go mod tidy'.

### CODE REVIEW

**Review by akhil-rane — COMMENTED** [review]
why not go1.17?

**Comment by joelddiaz** [comment]
> why not go1.17?
Just following along with the current golang build container that is used https://github.com/openshift/aws-pod-identity-webhook/blob/master/Dockerfile.rhel7#L1
Eventually, I expect some bot to upgrade this repo to a newer go verison, but for the time being, I thought it should match the rest of the repo.

**Comment by akhil-rane** [comment]
> > why not go1.17?
> > Just following along with the current golang build container that is used https://github.com/openshift/aws-pod-identity-webhook/blob/master/Dockerfile.rhel7#L1
> > Eventually, I expect some bot to upgrade this repo to a newer go verison, but for the time being, I thought it should match the rest of the repo.

There is open PR by the bot to update that. Do you think we should wait for that to merge?

**Comment by akhil-rane** [comment]
The PR to update golang container to 1.17 is now merged. I guess we can update here now :)

**Comment by joelddiaz** [comment]
Yes. let me close this and we'll start from scratch with the new go 1.17 that just merged

**Pull request closed without merging**
