### PR TITLE
Rebase master

### PR DESCRIPTION
**Pull request by joelddiaz**
rebase against upstream. reapply our carry patches

This was done by:
forking upstream into personal account
cloning fork: git clone git@github.com:joelddiaz/amazon-eks-pod-identity-webhook.git
add upstream remote: git remote add --fetch upstream https://github.com/aws/amazon-eks-pod-identity-webhook
add openshift remote: git remote add --fetch openshift https://github.com/openshift/aws-pod-identity-webhook.git

create branch for PR: git checkout -b rebase-master master

merge openshift/master into rebase-master using `ours` strategy: git merge -s ours openshift/master

Made a list of carry commits, and cherry-picked them into rebase-master branch.

### CODE REVIEW

**Comment by dgoodwin** [comment]
I gotta ask what direction we want to go long term here. Talking with Joel on Slack, this is based on what we do for OpenShift and Kube, he suspects because it keeps us constantly evaluating if we want to keep carrying each patch.

Git is made to do this far easier, just fetch the upstream, and git merge it into our repo. Conflicts get resolved once and then you're good to go. We keep carrying what we were carrying before. This is a lot easier each time we want to do a rebase.

What do folks think, is the more heavy handed process worth it for what we need out of this repo or do we feel we're better off doing it the quick and easy way git is intended to help us with.

cc @sjenning

**Comment by dgoodwin** [comment]
I think this is up to you @joelddiaz , are you ok with this process? I guess we can always do it another way later if desired and the opposite is not as true.

/lgtm

/hold

Remove hold if you're feeling this is good enough. Looks like we're only carrying a couple patches.

**Comment by joelddiaz** [comment]
/unhold
i think we can run with this for now. if nothing else, we at least have to acknowledge and/or investigate if/when one of our upstream PRs don't merge.

**Pull request merged**
