### PR TITLE
Update OWNERS

### PR DESCRIPTION
**Pull request by 2uasimojo**
/assign @suhanime

### CODE REVIEW

**Comment by 2uasimojo** [comment]
Well cool. Now we need someone who's authorized to either add labels or force merge. I don't know if that's based on repo permissions or the OWNERS file; if the latter, only @abutcher can help us.

**Comment by abutcher** [comment]
I can't interact with labels on this PR or force merge.

**Comment by 2uasimojo** [comment]
@sjenning do you have the power to make this go?

**Pull request merged**
